//
//  Bounds+JsonGen.swift
//
//  Auto generated by swift-json-gen on Mon, 24 Apr 2017 19:49:15 GMT
//  See for details: https://github.com/tomlokhorst/swift-json-gen
//

import Foundation
import Statham

extension Bounds {
  public static func decodeJson(_ json: Any) throws -> Bounds {
    let decoder = try JsonDecoder(json: json)

    let _latmin = try decoder.decode("latmin", decoder: Double.decodeJson)
    let _latmax = try decoder.decode("latmax", decoder: Double.decodeJson)
    let _lonmin = try decoder.decode("lonmin", decoder: Double.decodeJson)
    let _lonmax = try decoder.decode("lonmax", decoder: Double.decodeJson)

    guard
      let latmin = _latmin,
      let latmax = _latmax,
      let lonmin = _lonmin,
      let lonmax = _lonmax
    else {
      throw JsonDecodeError.structErrors(type: "Bounds", errors: decoder.errors)
    }

    return Bounds(latmin: latmin, latmax: latmax, lonmin: lonmin, lonmax: lonmax)
  }

  public func encodeJson() -> [String: Any] {
    var dict: [String: Any] = [:]

    dict["latmin"] = latmin.encodeJson()
    dict["latmax"] = latmax.encodeJson()
    dict["lonmin"] = lonmin.encodeJson()
    dict["lonmax"] = lonmax.encodeJson()

    return dict
  }
}
