//
//  SuccessResponse+JsonGen.swift
//
//  Auto generated by swift-json-gen on Mon, 03 Apr 2017 19:19:59 GMT
//  See for details: https://github.com/tomlokhorst/swift-json-gen
//

import Foundation
import Statham

extension SuccessResult {
  static func decodeJson(_ json: Any) throws -> SuccessResult {
    let decoder = try JsonDecoder(json: json)

    let _success = try decoder.decode("success", decoder: Bool.decodeJson)

    guard let success = _success else {
      throw JsonDecodeError.structErrors(type: "SuccessResult", errors: decoder.errors)
    }

    return SuccessResult(success: success)
  }

  func encodeJson() -> [String: Any] {
    var dict: [String: Any] = [:]

    dict["success"] = success.encodeJson()

    return dict
  }
}
