disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - trailing_comma
  - nesting
  - redundant_string_enum_value # disabled because we want explicit keys for user defaults and keychain
  - identifier_name # please enable at some point because too many inconsitencies throughout the codebase 
  - type_name
  - opening_brace

line_length:
  warning: 400
  error: 600
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

identifier_name:
  excluded:
    - id

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - BuildTools
  - "**/R.generated.swift"