//
//  SuccessResponse+JsonGen.swift
//
//  Auto generated by swift-json-gen on Mon, 26 Oct 2015 20:34:07 GMT
//  See for details: https://github.com/tomlokhorst/swift-json-gen
//

import Foundation

extension SuccessResult {
  static func decodeJson(json: AnyObject) -> SuccessResult? {
    guard let dict = json as? [String : AnyObject] else {
      assertionFailure("json not a dictionary")
      return nil
    }

    guard let success_field: AnyObject = dict["success"] else {
      assertionFailure("field 'success' is missing")
      return nil
    }
    guard let success: Bool = Bool.decodeJson(success_field) else {
      assertionFailure("field 'success' is not a Bool")
      return nil
    }

    return SuccessResult(success: success)
  }

  func encodeJson() -> [String: AnyObject] {
    var dict: [String: AnyObject] = [:]

    dict["success"] = success.encodeJson()

    return dict
  }
}
