disabled_rules:
  - line_length
  - identifier_name
  - missing_docs
  - redundant_string_enum_value
opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - overridden_super_call
  - force_unwrapping
  - redundant_nil_coalesing
  - switch_case_on_newline
excluded:
 - HoelangTotTrein2/R.generated.swift
file_length:
  warning: 300
  error: 9999

empty_count:
  severity: warning