//
//  HistoryType+JsonGen.swift
//
//  Auto generated by swift-json-gen on Mon, 24 Apr 2017 19:49:15 GMT
//  See for details: https://github.com/tomlokhorst/swift-json-gen
//

import Foundation
import Statham
//
//extension HistoryType {
//  public static func decodeJson(_ json: Any) throws -> HistoryType {
//    guard let rawValue = json as? Int else {
//      throw Jsonde
//    }
//    guard let value = HistoryType(rawValue: rawValue) else {
//      throw JsonDecodeError.wrongEnumRawValue(rawValue: rawValue, enumType: "HistoryType")
//    }
//
//    return value
//  }
//
//  public func encodeJson() -> Int {
//    return rawValue
//  }
//}
